// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFileHash = `-- name: CreateFileHash :one
INSERT INTO files (id, file_name, directory, created_at, updated_at, last_change, hash)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, file_name, directory, created_at, updated_at, last_change, hash
`

type CreateFileHashParams struct {
	ID         uuid.UUID
	FileName   string
	Directory  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastChange time.Time
	Hash       string
}

func (q *Queries) CreateFileHash(ctx context.Context, arg CreateFileHashParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFileHash,
		arg.ID,
		arg.FileName,
		arg.Directory,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastChange,
		arg.Hash,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChange,
		&i.Hash,
	)
	return i, err
}

const deleteFiles = `-- name: DeleteFiles :exec
DELETE FROM files
`

func (q *Queries) DeleteFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFiles)
	return err
}

const getFileHashByName = `-- name: GetFileHashByName :one
SELECT id, file_name, directory, created_at, updated_at, last_change, hash FROM files
WHERE hash = $1 LIMIT 1
`

func (q *Queries) GetFileHashByName(ctx context.Context, hash string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileHashByName, hash)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChange,
		&i.Hash,
	)
	return i, err
}

const updateFileChecked = `-- name: UpdateFileChecked :exec
UPDATE files
SET updated_at = $1
WHERE id = $2
`

type UpdateFileCheckedParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateFileChecked(ctx context.Context, arg UpdateFileCheckedParams) error {
	_, err := q.db.ExecContext(ctx, updateFileChecked, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileHash = `-- name: UpdateFileHash :exec
UPDATE files
SET updated_at = $1, last_change = $1, hash = $2
WHERE id = $3
`

type UpdateFileHashParams struct {
	UpdatedAt time.Time
	Hash      string
	ID        uuid.UUID
}

func (q *Queries) UpdateFileHash(ctx context.Context, arg UpdateFileHashParams) error {
	_, err := q.db.ExecContext(ctx, updateFileHash, arg.UpdatedAt, arg.Hash, arg.ID)
	return err
}
