// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFileHash = `-- name: CreateFileHash :one
INSERT INTO files (id, file_name, directory, created_at, updated_at, last_change, hash)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, file_name, directory, created_at, updated_at, last_change, hash
`

type CreateFileHashParams struct {
	ID         uuid.UUID
	FileName   string
	Directory  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastChange time.Time
	Hash       string
}

func (q *Queries) CreateFileHash(ctx context.Context, arg CreateFileHashParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFileHash,
		arg.ID,
		arg.FileName,
		arg.Directory,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastChange,
		arg.Hash,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChange,
		&i.Hash,
	)
	return i, err
}

const deleteFiles = `-- name: DeleteFiles :exec
DELETE FROM files
`

func (q *Queries) DeleteFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFiles)
	return err
}

const getFileByName = `-- name: GetFileByName :one
SELECT id, file_name, directory, created_at, updated_at, last_change, hash FROM files
WHERE file_name = $1 AND directory = $2 LIMIT 1
`

type GetFileByNameParams struct {
	FileName  string
	Directory string
}

func (q *Queries) GetFileByName(ctx context.Context, arg GetFileByNameParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByName, arg.FileName, arg.Directory)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChange,
		&i.Hash,
	)
	return i, err
}

const getFileNameByID = `-- name: GetFileNameByID :one
SELECT file_name FROM files
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFileNameByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFileNameByID, id)
	var file_name string
	err := row.Scan(&file_name)
	return file_name, err
}

const getHashByID = `-- name: GetHashByID :one
SELECT hash FROM files
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHashByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getHashByID, id)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const updateFileChecked = `-- name: UpdateFileChecked :exec
UPDATE files
SET updated_at = $1
WHERE id = $2
`

type UpdateFileCheckedParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateFileChecked(ctx context.Context, arg UpdateFileCheckedParams) error {
	_, err := q.db.ExecContext(ctx, updateFileChecked, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileHash = `-- name: UpdateFileHash :exec
UPDATE files
SET updated_at = $1, last_change = $1, hash = $2
WHERE id = $3
`

type UpdateFileHashParams struct {
	UpdatedAt time.Time
	Hash      string
	ID        uuid.UUID
}

func (q *Queries) UpdateFileHash(ctx context.Context, arg UpdateFileHashParams) error {
	_, err := q.db.ExecContext(ctx, updateFileHash, arg.UpdatedAt, arg.Hash, arg.ID)
	return err
}
