// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createHistoryEntry = `-- name: CreateHistoryEntry :one
INSERT INTO history (id, previous_hash, current_hash, date_change, file_id)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, previous_hash, current_hash, date_change, file_id
`

type CreateHistoryEntryParams struct {
	ID           uuid.UUID
	PreviousHash string
	CurrentHash  string
	DateChange   time.Time
	FileID       uuid.UUID
}

func (q *Queries) CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (History, error) {
	row := q.db.QueryRowContext(ctx, createHistoryEntry,
		arg.ID,
		arg.PreviousHash,
		arg.CurrentHash,
		arg.DateChange,
		arg.FileID,
	)
	var i History
	err := row.Scan(
		&i.ID,
		&i.PreviousHash,
		&i.CurrentHash,
		&i.DateChange,
		&i.FileID,
	)
	return i, err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM history
`

func (q *Queries) DeleteHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteHistory)
	return err
}

const getHistoryByDateChanged = `-- name: GetHistoryByDateChanged :many
SELECT id, previous_hash, current_hash, date_change, file_id FROM history
ORDER BY date_change
`

func (q *Queries) GetHistoryByDateChanged(ctx context.Context) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByDateChanged)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.PreviousHash,
			&i.CurrentHash,
			&i.DateChange,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoryByFileID = `-- name: GetHistoryByFileID :many
SELECT id, previous_hash, current_hash, date_change, file_id FROM history
WHERE file_id = $1
`

func (q *Queries) GetHistoryByFileID(ctx context.Context, fileID uuid.UUID) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.PreviousHash,
			&i.CurrentHash,
			&i.DateChange,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
