// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ignore_list.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIgnoreEntry = `-- name: CreateIgnoreEntry :one
INSERT INTO ignorelist (id, file_name, directory, date_added)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, file_name, directory, date_added
`

type CreateIgnoreEntryParams struct {
	ID        uuid.UUID
	FileName  string
	Directory string
	DateAdded time.Time
}

func (q *Queries) CreateIgnoreEntry(ctx context.Context, arg CreateIgnoreEntryParams) (Ignorelist, error) {
	row := q.db.QueryRowContext(ctx, createIgnoreEntry,
		arg.ID,
		arg.FileName,
		arg.Directory,
		arg.DateAdded,
	)
	var i Ignorelist
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.DateAdded,
	)
	return i, err
}

const deleteIgnoreItemByID = `-- name: DeleteIgnoreItemByID :exec
DELETE FROM ignorelist
WHERE ID = $1
`

func (q *Queries) DeleteIgnoreItemByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIgnoreItemByID, id)
	return err
}

const deleteIgnoreList = `-- name: DeleteIgnoreList :exec
DELETE FROM ignorelist
`

func (q *Queries) DeleteIgnoreList(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteIgnoreList)
	return err
}

const getIgnoreListByDateAdded = `-- name: GetIgnoreListByDateAdded :many
SELECT id, file_name, directory, date_added FROM ignorelist
ORDER BY date_added
`

func (q *Queries) GetIgnoreListByDateAdded(ctx context.Context) ([]Ignorelist, error) {
	rows, err := q.db.QueryContext(ctx, getIgnoreListByDateAdded)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ignorelist
	for rows.Next() {
		var i Ignorelist
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Directory,
			&i.DateAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIgnoredItemByNameDirectory = `-- name: GetIgnoredItemByNameDirectory :one
SELECT id, file_name, directory, date_added FROM ignorelist
WHERE file_name = $1 AND directory = $2
`

type GetIgnoredItemByNameDirectoryParams struct {
	FileName  string
	Directory string
}

func (q *Queries) GetIgnoredItemByNameDirectory(ctx context.Context, arg GetIgnoredItemByNameDirectoryParams) (Ignorelist, error) {
	row := q.db.QueryRowContext(ctx, getIgnoredItemByNameDirectory, arg.FileName, arg.Directory)
	var i Ignorelist
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Directory,
		&i.DateAdded,
	)
	return i, err
}
