// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID         uuid.UUID
	FileName   string
	Directory  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	LastChange time.Time
	Hash       string
}

type History struct {
	ID           uuid.UUID
	PreviousHash string
	CurrentHash  string
	DateChange   time.Time
	FileID       uuid.UUID
}

type Ignorelist struct {
	ID        uuid.UUID
	FileName  string
	Directory string
	DateAdded time.Time
}
