package inputoutput

import (
	"fmt"
)

func PrintHelp() {
	fmt.Println("Available Commands:")
	fmt.Println("Scan:")
	fmt.Println("- scan file ./folder/example.txt")
	fmt.Println("     Scans a single file to calculate it's hash and stores it in the database")
	fmt.Println("- scan directory ./folder/")
	fmt.Println("     Scans the target directory storing all file hashes into the database")
	fmt.Println("Help:")
	fmt.Println("- help")
	fmt.Println("     Displays this help message")
	fmt.Println("History:")
	fmt.Println("- history")
	fmt.Println("     List all history entries")
	fmt.Println("- history ./folder/example.txt")
	fmt.Println("     List the history for a specific file")
	fmt.Println("Ignore:")
	fmt.Println("- ignore add ./folder/example.txt")
	fmt.Println("     Adds the specified file to the ignore list")
	fmt.Println("- ignore remove ./folder/example.txt")
	fmt.Println("     Removed the specified file from the ignore list")
	fmt.Println("- ignore list")
	fmt.Println("     Shows all items from the ignore list")
	fmt.Println("Reset:")
	fmt.Println("- reset")
	fmt.Println("     Resets the database")
	fmt.Println("Server:")
	fmt.Println("- server start")
	fmt.Println("     Launches a local webserver which host a page at http://localhost:8080/report")
	fmt.Println("     The report displays the history in a table format")
	fmt.Println("- server stop")
	fmt.Println("     Stops the local server")
	fmt.Println("Quit:")
	fmt.Println("- quit")
	fmt.Println("     Exits the program")
}
